[build]
  # Build command - direct Vite build with Netlify config
  command = "npx vite build --config vite.config.netlify.ts"
  
  # Directory to publish - the built React app
  publish = "dist/public"

[build.environment]
  # Node.js version for any build processes
  NODE_VERSION = "18"
  # Ensure production build
  NODE_ENV = "production"

[[headers]]
  # Apply headers to all files
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Special headers for HTML files
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # CORS headers for game assets
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# Redirect rules for SPA behavior - handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
# Form handling (for future contact forms if needed)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"

# Deploy previews configuration
[context.deploy-preview]
  command = ""

# Branch deploys
[context.branch-deploy]
  command = ""